### ISSUE TITLE
[使用默认播放器模式] 在开始播放后 13 秒才会生效（变为宽屏、全屏什么的）

### ISSUE THREAD

**Issue by XIU2** [the1812/Bilibili-Evolved#2225]
### \# 关于哪一项功能
`使用默认播放器模式`

### 问题描述
在指定 `默认播放器模式` 为宽屏（或全屏）后，打开任何视频页开始播放后 **13 秒**才会正确变为宽屏（或全屏）。
同时，`播放时应用模式` 及 `播放时自动关灯` 都和上面说的一样。
而这个情况是从前几天才开始的。
另外，鼠标中键后台打开视频页时，以前视频默认是不播放的（只有点开该标签页才会开始播放），但是现在都会**自动播放**了。。。

### \# 脚本版本
预览版 1.12.16

### \# 浏览器版本
Chrome 86.0.4240.198

### \# 播放器版本
2.65.0-4d34a690

### \# 错误信息
没有显示内部错误消息，Console 也没有该脚本的错误输出。

**Comment by panpando** [comment]
在播放器齿轮里禁用HEVC

**Comment by SEVLT** [comment]
> 在播放器齿轮里禁用HEVC

非常感谢！帮我的大忙了！

**Comment by yanglihao347** [comment]
> 在播放器齿轮里禁用HEVC

实测有用！感谢

**Comment by edc2766** [comment]
感谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月30日(星期一) 中午11:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [the1812/Bilibili-Evolved] [使用默认播放器模式] 在开始播放后 13 秒才会生效（变为宽屏、全屏什么的） (#2225)





  
在播放器齿轮里禁用HEVC
  
实测有用！感谢
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by edc2766** [comment]
感谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月28日(星期六) 中午1:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [the1812/Bilibili-Evolved] [使用默认播放器模式] 在开始播放后 13 秒才会生效（变为宽屏、全屏什么的） (#2225)





 
在播放器齿轮里禁用HEVC
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by edc2766** [comment]
感谢回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月28日(星期六) 下午2:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [the1812/Bilibili-Evolved] [使用默认播放器模式] 在开始播放后 13 秒才会生效（变为宽屏、全屏什么的） (#2225)





  
在播放器齿轮里禁用HEVC
  
非常感谢！帮我的大忙了！
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
